'use client';

import { useState, useEffect, useImperativeHandle, forwardRef } from 'react';
import { Save, Share2 } from 'lucide-react';
import { getTodaysPoem} from '../utils/DailyPoem';
import { Calendar } from 'lucide-react';
import { hslToHex } from '../utils/colorUtils';


import Aurora from "./Aurora";
import PoemDetails from "./PoemDetails";

interface PoemCardProps {
  color: string | null;
  colorName: string | null;
  onPoemGenerated?: (color: string, colorName: string, poem: string) => void;
}

export interface PoemCardRef {
  generatePoem: () => void;
}

const today = new Date();

const formmattedDate = today.toLocaleDateString('en-US', {
  month: 'long',
  day: 'numeric',
  year: 'numeric',
});

const todaysPoem = getTodaysPoem();

const PoemCard = forwardRef<PoemCardRef, PoemCardProps>(function PoemCard({ color, colorName, onPoemGenerated }, ref) {
  const [poem, setPoem] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [showGenerated, setShowGenerated] = useState(false);

  // Save poem handler
  const handleSavePoem = () => {
    if (!poem || !colorName) return;
    
    // Create downloadable text file
    const poemText = `${colorName} Poem\n\n${poem}\n\nGenerated by ColorPoet`;
    const blob = new Blob([poemText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${colorName}-poem.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  // Share poem handler
  const handleSharePoem = async () => {
    if (!poem || !colorName) return;
    
    const shareText = `${colorName} Poem:\n\n${poem}\n\nGenerated by ColorPoet`;
    
    if (navigator.share) {
      try {
        await navigator.share({
          title: `${colorName} Poem`,
          text: shareText,
        });
      } catch {
        console.log('Share cancelled or failed');
      }
    } else {
      // Fallback: copy to clipboard
      await navigator.clipboard.writeText(shareText);
      alert('Poem copied to clipboard!');
    }
  };

  // Dynamic font size based on poem length
  const getPoemFontSize = (text: string | null) => {
    if (!text) return 'text-xl';
    const length = text.length;
    if (length < 150) return 'text-xl';
    if (length < 250) return 'text-lg';
    if (length < 400) return 'text-lg';
    return 'text-lg';
  };

  // Dynamic font size for daily poem
  const getDailyPoemFontSize = () => {
    const totalLength = todaysPoem.lines.join('').length;
    if (totalLength < 200) return 'text-lg';
    if (totalLength < 400) return 'text-base';
    return 'text-sm';
  };

  // Generate poem function that can be called externally
  const generatePoem = async () => {
    if (!color || !colorName) return;
    
    setIsLoading(true);
    setError(null);

    try {
      // Send source poem text to API
      const sourcePoemText = todaysPoem.lines.join('\n');
      
      const response = await fetch('/api/poem', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({ 
          color, 
          colorName,
          sourcePoem: sourcePoemText,
          sourcePoemTitle: todaysPoem.title,
          sourcePoemAuthor: todaysPoem.author
        }),
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || 'Failed to generate poem');
      }

      const data = await response.json();
      setPoem(data.poem);
      setShowGenerated(true); // Auto-switch to generated poem

      if (onPoemGenerated) {
        onPoemGenerated(color, colorName, data.poem);
      }
    } catch (err) {
      console.error('Error generating poem:', err);
      setError(err instanceof Error ? err.message : 'An unknown error occurred');
    } finally {
      setIsLoading(false);
    }
  };

  // Expose generatePoem function to parent via ref
  useImperativeHandle(ref, () => ({
    generatePoem
  }));

  // Clear poem when color changes
  useEffect(() => {
    if (!color || !colorName) {
      setPoem(null);
      setError(null);
      setShowGenerated(false); // Reset to original when color changes
    }
  }, [color, colorName]); // dependant on color and colorNames

    


  return (
    <div className="w-full h-full flex flex-col gap-2 p-0">
      {/* Poem Container with Aurora Background */}
      <div 
        className="rounded-2xl flex-1 min-h-0 flex flex-col w-full overflow-hidden relative border border-white/10 shadow-2xl"
       
      >

        {/* Aurora Background */}
        <div className="absolute inset-0 pointer-events-none">
          <Aurora amplitude={1.2} blend={0.5} />
        </div>
        
        {/* Glassmorphism Overlay */}
        <div className="absolute inset-0 bg-linear-to-br from-slate-950/60 via-slate-900/50 to-slate-950/60 backdrop-blur-xs"></div>
        
        {/* Content */}
        <div className="relative z-10 p-4 pb-0 flex flex-col flex-1 min-h-0">
        
        {/* Date Header */}
        <div className="text-center mb-6 border-b border-slate-700/50 pb-4 shrink-0">
          <p className="text-slate-400 text-sm uppercase tracking-widest mb-2">
            {showGenerated && poem ? 'Color Poem' : "Today's Poem"}
          </p>
          <div className="flex items-center justify-center gap-2">
            {!showGenerated && <Calendar className="w-5 h-5 text-slate-400" />}
            {showGenerated && poem && color && (
              <div 
                className="w-6 h-6 rounded border-2 border-white/50 shadow-lg"
                style={{ backgroundColor: color }}
              />
            )}
            <h2 className="text-2xl font-ui font-light text-white mb-1">
              {showGenerated && poem && color ? hslToHex(color) : formmattedDate}
            </h2>
          </div>
          <div className="flex items-center justify-center gap-2 mt-4">
            <div className="h-px w-12 bg-linear-to-r from-transparent to-slate-600"></div>
            <span className="text-slate-500 text-xs">✦</span>
            <div className="h-px w-12 bg-linear-to-l from-transparent to-slate-600"></div>
          </div>
        </div>

        {/* Two Column Layout: Poem + Details */}
        <div className="flex-1 min-h-0 flex gap-4 overflow-hidden">
          
          {/* Left Column: Poem Content */}
          <div className="flex-1 flex flex-col items-center justify-center min-h-0 overflow-y-auto px-4">
            
            {/* Loading State */}
            {isLoading && showGenerated && (
              <div className="flex-1 flex items-center justify-center">
                <p className="text-slate-500 text-sm">Generating poem...</p>
              </div>
            )}

            {/* Error State */}
            {error && showGenerated && (
              <div className="flex-1 flex items-center justify-center">
                <p className="text-red-400 text-sm">{error}</p>
              </div>
            )}

            {/* Original Poem Display */}
            {!showGenerated && !isLoading && (
              <div className={`flex flex-col items-center justify-center w-full font-poem ${getDailyPoemFontSize()} leading-relaxed text-slate-200 text-center space-y-1 max-w-xl animate-fade-slide-in`}>
                {todaysPoem.lines.map((line, index) => (
                  <p key={index} className="transition-all hover:text-white">
                    {line}
                  </p>
                ))}
              </div>
            )}

            {/* Generated Poem Display */}
            {showGenerated && poem && !isLoading && !error && (
              <div className={`flex flex-col items-center justify-center w-full font-poem ${getPoemFontSize(poem)} leading-relaxed text-slate-200 text-center space-y-1 max-w-xl animate-fade-slide-in`}>
                {poem.split('\n').map((line, index) => (
                  <p key={index} className="transition-all hover:text-white">
                    {line}
                  </p>
                ))}
              </div>
            )}
          </div>

          {/* Right Column: Poem Details */}
          <div className="w-80 shrink-0 overflow-y-auto">
            <PoemDetails
              showGenerated={showGenerated && !!poem}
              color={color}
              colorName={colorName}
              poemTitle={todaysPoem.title}
              poemAuthor={todaysPoem.author}
              date={formmattedDate}
            />
          </div>
        </div>
        </div>
        
        {/* Action Bar */}
        <div className="relative z-10 w-full grid grid-cols-3 gap-2 border-t border-slate-700/50 bg-slate-950/40 backdrop-blur-sm p-3 shrink-0">
          
          {/* Section 1: Original Button */}
          <button
            onClick={() => setShowGenerated(false)}
            disabled={!poem}
            className={`px-3 py-2 rounded-lg text-xs font-medium transition-all  cursor-pointer  ${
              !showGenerated && poem
                ? 'bg-blue-500/30 text-white'
                : 'bg-slate-800/50 text-slate-400 hover:bg-slate-700/50 disabled:opacity-40 disabled:cursor-not-allowed'
            }`}
          >
            Original
          </button>

          {/* Section 2: Generated Button */}
          <button
            onClick={() => setShowGenerated(true)}
            disabled={!poem}
            className={`px-3 py-2 rounded-lg text-xs font-medium  flex items-center justify-center gap-1.5 cursor-pointer   transition-all ease-in-out ${
              showGenerated && poem
                ? 'bg-blue-500/30 text-white'
                : 'bg-slate-800/50 text-slate-400 hover:bg-slate-700/50 disabled:opacity-40 disabled:cursor-not-allowed'
            }`}
          >
            {color && <span className="inline-block w-2.5 h-2.5 rounded-full" style={{ backgroundColor: color }}></span>}
            Generated
          </button>

          {/* Section 3: Action Buttons */}
          <div className="flex gap-2">
            <button
              onClick={handleSavePoem}
              disabled={!poem}
              className="flex-1 flex items-center justify-center gap-1.5 px-3 py-2 bg-slate-800/50 text-slate-300 rounded-lg text-xs font-medium hover:bg-slate-700/50 transition-all disabled:opacity-40 disabled:cursor-not-allowed"
              title="Save poem"
            >
              <Save className="w-4 h-4" />
              Save
            </button>
            <button
              onClick={handleSharePoem}
              disabled={!poem}
              className="flex-1 flex items-center justify-center gap-1.5 px-3 py-2 bg-slate-800/50 text-slate-300 rounded-lg text-xs font-medium hover:bg-slate-700/50 transition-all disabled:opacity-40 disabled:cursor-not-allowed"
              title="Share poem"
            >
              <Share2 className="w-4 h-4" />
              Share
            </button>
          </div>
        </div>
      {/* End Action Bar */}
      
      </div>
      {/* End Poem Card Container */}
    </div>
  );
});

export default PoemCard;
